export const products = [
  {
    id: 1,
    name: 'Sovereign Automatic',
    brand: 'CHRONOHAUS',
    category: ['luxury', 'automatic', 'men'],
    price: 124999,
    image: '/images/watch-1.jpg',
    description: 'A masterpiece of mechanical engineering with 72-hour power reserve.',
    specs: {
      movement: 'Automatic Calibre CH-01',
      case: '41mm Stainless Steel 316L',
      crystal: 'Sapphire with AR coating',
      waterResistance: '100m / 10 ATM',
      dial: 'Sunburst Black',
      strap: 'Italian Leather',
      warranty: '5 Years International',
    },
    featured: true,
    newArrival: false,
  },
  {
    id: 2,
    name: 'Meridian Chronograph',
    brand: 'CHRONOHAUS',
    category: ['luxury', 'chronograph', 'men'],
    price: 159999,
    image: '/images/watch-2.jpg',
    description: 'Precision timing meets timeless design in this chronograph collection.',
    specs: {
      movement: 'Automatic Chronograph Calibre CH-02',
      case: '43mm Titanium Grade 5',
      crystal: 'Double-domed Sapphire',
      waterResistance: '200m / 20 ATM',
      dial: 'Matte Navy Blue',
      strap: 'Bracelet / Rubber',
      warranty: '5 Years International',
    },
    featured: false,
    newArrival: true,
  },
  {
    id: 3,
    name: 'Aura Ceramic',
    brand: 'CHRONOHAUS',
    category: ['luxury', 'automatic', 'women'],
    price: 89999,
    image: '/images/watch-3.jpg',
    description: 'Elegance redefined with high-tech ceramic and diamond indices.',
    specs: {
      movement: 'Automatic Calibre CH-03',
      case: '36mm High-Tech Ceramic',
      crystal: 'Sapphire',
      waterResistance: '50m / 5 ATM',
      dial: 'Mother of Pearl',
      strap: 'Ceramic Bracelet',
      warranty: '5 Years International',
    },
    featured: true,
    newArrival: false,
  },
  {
    id: 4,
    name: 'Navigator GMT',
    brand: 'CHRONOHAUS',
    category: ['automatic', 'men'],
    price: 109999,
    image: '/images/watch-4.jpg',
    description: 'Dual timezone capability for the modern traveller.',
    specs: {
      movement: 'Automatic GMT Calibre CH-04',
      case: '40mm Steel & Ceramic',
      crystal: 'Sapphire',
      waterResistance: '100m / 10 ATM',
      dial: 'Sunburst Green',
      strap: 'Stainless Steel',
      warranty: '5 Years International',
    },
    featured: false,
    newArrival: true,
  },
  {
    id: 5,
    name: 'Classique Hand-Wind',
    brand: 'CHRONOHAUS',
    category: ['classic', 'men'],
    price: 74999,
    image: '/images/watch-5.jpg',
    description: 'Traditional watchmaking with a thin hand-wound movement.',
    specs: {
      movement: 'Hand-wound Calibre CH-05',
      case: '39mm Rose Gold PVD',
      crystal: 'Box Sapphire',
      waterResistance: '30m / 3 ATM',
      dial: 'Enamel White',
      strap: 'Alligator Leather',
      warranty: '5 Years International',
    },
    featured: false,
    newArrival: false,
  },
  {
    id: 6,
    name: 'Horizon Smart',
    brand: 'CHRONOHAUS',
    category: ['smart', 'men', 'women'],
    price: 34999,
    image: '/images/watch-6.jpg',
    description: 'Luxury meets technology with health tracking and notification suite.',
    specs: {
      movement: 'Digital Hybrid',
      case: '42mm Aluminium',
      crystal: 'Sapphire Glass',
      waterResistance: '50m / 5 ATM',
      dial: 'AMOLED Touchscreen',
      strap: 'Quick-release Silicone / Leather',
      warranty: '2 Years',
    },
    featured: false,
    newArrival: true,
  },
  {
    id: 7,
    name: 'Nocturne Diver',
    brand: 'CHRONOHAUS',
    category: ['luxury', 'automatic', 'men'],
    price: 199999,
    image: '/images/watch-7.jpg',
    description: 'Professional diving instrument rated to 600m depth.',
    specs: {
      movement: 'Automatic Calibre CH-07',
      case: '44mm Ceramic & Titanium',
      crystal: 'Sapphire with AR coating',
      waterResistance: '600m / 60 ATM',
      dial: 'Luminous Black',
      strap: 'Rubber Dive Strap',
      warranty: '5 Years International',
    },
    featured: true,
    newArrival: false,
  },
  {
    id: 8,
    name: 'Solstice Dress',
    brand: 'CHRONOHAUS',
    category: ['classic', 'women'],
    price: 59999,
    image: '/images/watch-8.jpg',
    description: 'Slim profile meets feminine grace in this dress watch.',
    specs: {
      movement: 'Quartz Calibre CH-08',
      case: '34mm Polished Steel',
      crystal: 'Sapphire',
      waterResistance: '30m / 3 ATM',
      dial: 'Champagne',
      strap: 'Mesh Bracelet',
      warranty: '3 Years',
    },
    featured: false,
    newArrival: false,
  },
]

export const categories = [
  { id: 'all', label: 'All' },
  { id: 'men', label: "Men's" },
  { id: 'women', label: "Women's" },
  { id: 'luxury', label: 'Luxury' },
  { id: 'automatic', label: 'Automatic' },
  { id: 'chronograph', label: 'Chronograph' },
  { id: 'classic', label: 'Classic' },
  { id: 'smart', label: 'Smart' },
]

export const formatPrice = (price) =>
  new Intl.NumberFormat('en-IN', {
    style: 'currency',
    currency: 'INR',
    maximumFractionDigits: 0,
  }).format(price)
